### ISSUE TITLE
IDK a lot of things

### ISSUE THREAD

**Issue by Blade-Dagger** [AymanLyesri/hyprland-conf#105]
i use update then reboot and appear those things. 
![image](https://github.com/user-attachments/assets/8079d2e7-ce98-4dc0-849a-9a9ccab36a6f)

**Comment by AymanLyesri** [comment]
run
```
rm -rf $HOME/.config/hypr/configs/custom/*
```
and let me know

**Comment by AymanLyesri** [comment]
show the output of 
```
pacman -Q hyprland
```

**Comment by Blade-Dagger** [comment]
hyprland 0.45.0-1

**Comment by AymanLyesri** [comment]
thats strange it says 0.44 is the latest for me 
![image](https://github.com/user-attachments/assets/f6857d76-a066-449f-afc3-4aedf8e26644)
r u sure u installed hyprland not hyprland-git

**Comment by Blade-Dagger** [comment]
._. i have hyprland no hyprland git

**Comment by AymanLyesri** [comment]
fixed, update and let me know

**Comment by Blade-Dagger** [comment]
i update, everything ok. thanks
