### ISSUE TITLE
Applications not opening

### ISSUE THREAD

**Issue by tlg-tg** [AymanLyesri/hyprland-conf#106]
So the current problem I'm facing is that applications that are bound to select workspaces do not open on that workspace.

**Comment by AymanLyesri** [comment]
[these](https://github.com/AymanLyesri/hyprland-conf/blob/master/.config/hypr/configs/window_rules.conf) are the only apps that will open at specific work-spaces every time, if u referring to the browser and discord client, run the install script, say no to all and choose the browser/discord client u want

**Comment by tlg-tg** [comment]
Oh ok so now it's built in to the install script

**Comment by tlg-tg** [comment]
Oh yeah what about the %u in browser file?

**Comment by AymanLyesri** [comment]
fixed, see [here](https://github.com/AymanLyesri/hyprland-conf/issues/102)

**Comment by tlg-tg** [comment]
Aha ok thanks for the help
