### ISSUE TITLE
Quick launcher hiding

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#108]
Quick launcher doesn't always hide upon mouse removal.

**Comment by AymanLyesri** [comment]
fixed, try it and let me know

**Comment by michaelnotjackson** [comment]
> fixed, try it and let me know

It became better, but it still can get stuck if you move your mouse away quickly

**Comment by AymanLyesri** [comment]
that's a limitation of ags, where it doesn't refresh quick enough to detect that the cursor is outside the border
This is a similar [issue](https://github.com/AymanLyesri/hyprland-conf/issues/29)

**Comment by michaelnotjackson** [comment]
Found another bug related to hiding. Launcher appears when mouse is near the bottom of the screen (not in the middle), but it doesn't hide when the mouse is removed

**Comment by AymanLyesri** [comment]
i don't quite understand, can u post a clip showing this bug

**Comment by michaelnotjackson** [comment]
> i don't quite understand, can u post a clip showing this bug


https://github.com/user-attachments/assets/168fff27-3f90-4f70-a6be-d1221511c37f

**Comment by AymanLyesri** [comment]
This is the intended behavior for now, much like the media widget, it will only hide if the cursor was removed from the widget itself and not the surrounding top/bottom, if i made it hover-able across the entire screen, any window that is in the background of it wont be clickable

**Comment by michaelnotjackson** [comment]
> This is the intended behavior for now, much like the media widget, it will only hide if the cursor was removed from the widget itself and not the surrounding top/bottom, if i made it hover-able across the entire screen, any window that is in the background of it wont be clickable

But isn't it already hover-able across entire bottom? My problem with it right now is that when you move your mouse to the bottom (not only in the middle) this widget appears and to make it disappear you have to move your mouse to the middle.

**Comment by AymanLyesri** [comment]
Only 1px is hoverable, but the widget is not, anyway, I'll make it fits the entire screen

**Comment by AymanLyesri** [comment]
fixed, update and let me know

**Comment by michaelnotjackson** [comment]
> fixed, update and let me know

Much better now, thanks!
