### ISSUE TITLE
Default package manager

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#11]
Right now updater script uses yay to check for updates. It would be nice if we were able to set default package manager during installation

**Comment by michaelnotjackson** [comment]
Oh, sorry. It seems I have an outdated version

**Comment by AymanLyesri** [comment]
No worries haha, always do a git pull whenever possible, i even made a reminder for updating the config through notifications, just click on the right panel and u'll find it, enjoy 
![image](https://github.com/user-attachments/assets/fc7a2644-4600-4e06-8682-40f0bbf884f3)
