### ISSUE TITLE
Step 3: reboot?

### ISSUE THREAD

**Issue by frederik-uni** [AymanLyesri/hyprland-conf#13]
Shouldn't everything be installed before the reboot? It doesn't make sense to me to reboot the system without everything installed. My guess is that it would make it unusable or at least almost with broken configs. The configs do not change anything that is required to install everything with yay
I haven't tested it

**Comment by optimisticubermenzsch** [comment]
How did you installed it? I didn't find any install.sh scripts? Can you tell me how did you installed it in a step by step method?

**Comment by frederik-uni** [comment]
@optimisticubermenzsch the update script

**Comment by optimisticubermenzsch** [comment]
The update scripts is not working as mentioned in the installation guide. I have done everything as mentioned. Not working.

**Comment by optimisticubermenzsch** [comment]
Can you help me install it?

**Comment by optimisticubermenzsch** [comment]
When I run ./update.sh, and I already installed yay but it say the pkglist.txt : no such file or directory.

**Comment by AymanLyesri** [comment]
> Shouldn't everything be installed before the reboot? It doesn't make sense to me to reboot the system without everything installed. My guess is that it would make it unusable or at least almost with broken configs. The configs do not change anything that is required to install everything with yay I haven't tested it

You're right, the package installation script should precede the reboot. I've updated the README to clarify the correct order.

**Comment by AymanLyesri** [comment]
> When I run ./update.sh, and I already installed yay but it say the pkglist.txt : no such file or directory.

Please make sure to follow the installation guide in the README carefully, step by step.
