### ISSUE TITLE
Missing pkglist

### ISSUE THREAD

**Issue by TaylorNova02** [AymanLyesri/hyprland-conf#2]
Hey, I think you forgot to add the Package List.
Could you add it?
I really like your rice, but one question why is there a swastika in [.config/hypr/neofetch](https://github.com/AymanLyesri/hyprland-conf/tree/master/.config/hypr/neofetch)?
Sorry I'm German and really cautious about it.

KR

Nova

**Comment by TaylorNova02** [comment]
Didn't saw your ToDo in the README sorry.

**Comment by AymanLyesri** [comment]
It's now implemented, I will keep updating it with essential packages 📦

**Comment by AymanLyesri** [comment]
About the swastika.... Umm.... Edgy phase? 💀

**Comment by TaylorNova02** [comment]
Oh ok thanks.

You might should link the package list in the ReadMe
Otherwise it's hard to find. ^^
Anyways thank you a lot for this awesome 🌾
