### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tlg-tg** [AymanLyesri/hyprland-conf#25]
So my problem is that I firstly installed vanilla arch no de or anything and then ran the setup script and it was not working also after I did install hyprland and the issue presisted

**Comment by tlg-tg** [comment]
Ok so I installed different dotfiles from end-4 and then I installed these ones after and there seems to be an error on line 7 in hyprland.conf with the source

**Comment by AymanLyesri** [comment]
> So my problem is that I firstly installed vanilla arch no de or anything and then ran the setup script and it was not working also after I did install hyprland and the issue presisted

please share the output of the install script so that i could help + hyprland should be installed its kinda obvious

> Ok so I installed different dotfiles from end-4 and then I installed these ones after and there seems to be an error on line 7 in hyprland.conf with the source

I'll fix it in the next commit (10min)

**Comment by tlg-tg** [comment]
So I re run the script no and there is an error while installing blueman as it is an invalid or corrupted package

**Comment by AymanLyesri** [comment]
> So I re run the script no and there is an error while installing blueman as it is an invalid or corrupted package

![image](https://github.com/user-attachments/assets/eb6aa139-e9d6-4256-a94c-770937ca9829)

blueman is a valid package (at least for me)
try installing it separately like shown above

**Comment by tlg-tg** [comment]
Ok oh and in the commit that you just posted there is no more install script

**Comment by tlg-tg** [comment]
There is nothing except blank on display in terminal there are errors 
![image](https://github.com/user-attachments/assets/dbe22d0f-0935-4870-8bab-0e9445940e55)
