### ISSUE TITLE
.config/btop/apply.sh is faulty

### ISSUE THREAD

**Issue by TaylorNova02** [AymanLyesri/hyprland-conf#3]
Hey just for your information,
Your [apply.sh](https://github.com/AymanLyesri/hyprland-conf/blob/master/.config/btop/apply.sh) is faulty if you clone all of your files.
Since your hypr folder doesn't contain a btop folder.

Kind regards Nova

P.S. sorry for making 2 Tickets within a month ^^'

**Comment by AymanLyesri** [comment]
yeah, I'll delete all the apply.sh files, they served there purpose before changing the whole config filesystem structure,
e.g: now when u clone the config, the btop folder get placed directly in its appropriate directory

Keep the tickets coming, i love fixing things ❤️
