### ISSUE TITLE
Suggsetions

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#35]
1. Return ability to choose random wallpaper
2. Add ability to specify package manager during installation via install.sh

**Comment by AymanLyesri** [comment]
> 1. Return ability to choose random wallpaper

Going to be added in the next pull request

 > 2. Add ability to specify package manager during installation via install.sh
 
 Low priority but will be added don't worry, maybe today

**Comment by AymanLyesri** [comment]
> 1. Return ability to choose random wallpaper

its pushed, check it out and let me know

**Comment by michaelnotjackson** [comment]
Now ags can't start with this error:
```

(com.github.Aylur.ags:2490): Gjs-Console-CRITICAL **: 17:35:15.087: 1 | import { Cancellable, Subprocess } from "types/@girs/gio-2.0/gio-2.0.cjs"
                                            ^
error: Could not resolve: "types/@girs/gio-2.0/gio-2.0.cjs". Maybe you need to "bun install"?
    at /home/michael/.config/ags/widgets/Update.ts:1:41
```

**Comment by michaelnotjackson** [comment]
> Now ags gives this error on start and crashes:
> 
> ```
> 
> (com.github.Aylur.ags:2490): Gjs-Console-CRITICAL **: 17:35:15.087: 1 | import { Cancellable, Subprocess } from "types/@girs/gio-2.0/gio-2.0.cjs"
>                                             ^
> error: Could not resolve: "types/@girs/gio-2.0/gio-2.0.cjs". Maybe you need to "bun install"?
>     at /home/michael/.config/ags/widgets/Update.ts:1:41
> ```

The problem here seems to be the Cancellable type. When I remove it from includes, ags starts and random wallpaper changes works fine. But battery icon is absent in this commit and ags gives this error:
```
(com.github.Aylur.ags:16095): Gjs-Console-WARNING **: 17:51:33.971: Error: can't assign "battery-level--10-symbolic" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
```

**Comment by AymanLyesri** [comment]
> > Now ags gives this error on start and crashes:
> > ```
> > 
> > (com.github.Aylur.ags:2490): Gjs-Console-CRITICAL **: 17:35:15.087: 1 | import { Cancellable, Subprocess } from "types/@girs/gio-2.0/gio-2.0.cjs"
> >                                             ^
> > error: Could not resolve: "types/@girs/gio-2.0/gio-2.0.cjs". Maybe you need to "bun install"?
> >     at /home/michael/.config/ags/widgets/Update.ts:1:41
> > ```
> 
> The problem here seems to be the Cancellable type. When I remove it from includes, ags starts and random wallpaper changes works fine. But battery icon is absent in this commit and ags gives this error:
> 
> ```
> (com.github.Aylur.ags:16095): Gjs-Console-WARNING **: 17:51:33.971: Error: can't assign "battery-level--10-symbolic" as icon, it is not a file nor a named icon
> set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
> bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
> hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
> _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
> ```

it been fixed
