### ISSUE TITLE
Keyboard layout

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#38]
After installing your config onto the clean arch system keyboard layout switching stopped working.
P.S. I added layouts that I need to the config files
P.P.S. Layout switching worked without any issues before I install your config, so it's not a problem with Hyprland

**Comment by AymanLyesri** [comment]
Keyboard layout configuration is done while installing the config
![image](https://github.com/user-attachments/assets/fb0ea817-4b68-4417-86b5-943508a639b1)
![image](https://github.com/user-attachments/assets/9bfb03bc-7a37-4047-ac22-714678daca81)
![image](https://github.com/user-attachments/assets/5a6f5fcf-09f1-4b0a-825d-e86a1b680375)


e.g: if u select `us` with `dvorak` it will create the config like so 
```
 kb_layout=us,us
 kb_variant=dvorak,
 ```
 ---
 I will add a more detailed keyboard configuration with multiple layouts

**Comment by michaelnotjackson** [comment]
Yeah, I know. It issue I'm facing is that with the same kb_layout, kb_options and kb_variant as on naked Hyprland (where I can switch layout) and in your config I'm unable to switch through selected layouts.
These are values in the input section of general.conf:
```
kb_layout=us,ru
kb_options=grp:alt_shift_toggle
kb_variant=qwerty,
```

**Comment by AymanLyesri** [comment]
Hmmm so same configuration but different behavior.
I personally never had this kind of problem (desktop, laptop or VM), we need somebody else to confirm this issue
Btw i made the ability to add multiples layouts to the keyboard configuration, it will be pushed in the next update

**Comment by michaelnotjackson** [comment]
Oi, I found what caused the issue! By default you have kb_model= and kb_rules= in general.conf. Because you don't pass values to these parameters Hyprland seems to ignore keyboard configuration

**Comment by michaelnotjackson** [comment]
And when kb_variant is set to qwerty it also doesn't for some reason

**Comment by AymanLyesri** [comment]
> Oi, I found what caused the issue! By default you have kb_model= and kb_rules= in general.conf. Because you don't pass values to these parameters Hyprland seems to ignore keyboard configuration

They will be removed in the next update

Am already planning to move the keyboard configuration to a separate file in the custom directory.
So when a user do a git pull to update the config, the keyboard configuration doesn't get overwritten by the repo changes.

![image](https://github.com/user-attachments/assets/ce03ead9-5113-4b4f-9882-2886a170ce05)




> And when kb_variant is set to qwerty it also doesn't for some reason

Yep same here, when i set us with qwerty it dosent recognise the other variant (dvorak) so i leave it empty like so :
```
kb_layout=us,us
kb_variant=dvorak, 
```
