### ISSUE TITLE
Absent battery widget

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#43]
https://github.com/AymanLyesri/hyprland-conf/blob/80130ba879d08bde4c34f9ab6da69d4a3b005d1d/.config/ags/widgets/bar/components/barRight.ts#L174
It seems like there should be some sort of battery widget, but it is not present
![image](https://github.com/user-attachments/assets/f8c59e8f-0d83-408c-bfcd-3fc8d8abab32)

**Comment by michaelnotjackson** [comment]
[ags.log](https://github.com/user-attachments/files/17410087/ags.log)
Here is the log

**Comment by michaelnotjackson** [comment]
I'm already up to date
![image](https://github.com/user-attachments/assets/097fe183-38a5-4582-8177-8bc8d41fe8d9)

**Comment by michaelnotjackson** [comment]
Updated, issue is still here. Here is the new log:
[ags.log](https://github.com/user-attachments/files/17410996/ags.log)

**Comment by AymanLyesri** [comment]
The errors related to battery widget had been fixed, i added new icons for displaying battery capacity.
Will be added in the next update
![image](https://github.com/user-attachments/assets/c8a9a1ae-80e4-4f51-872e-846011115eb0)
But it's strange that it always worked on my laptop, despite some warnings.

**Comment by michaelnotjackson** [comment]
Battery icon is still missing and there is no font installed by default to perceive unicode characters that you use for battery label
![image](https://github.com/user-attachments/assets/ee7794db-13ae-471a-880e-34dc81d7e2bf)
Here is new ags log:
[ags.log](https://github.com/user-attachments/files/17432817/ags.log)
