### ISSUE TITLE
Sidebar Image fail

### ISSUE THREAD

**Issue by Blade-Dagger** [AymanLyesri/hyprland-conf#45]
The image of the sidebar is very large and due to the size I ruin the bar and it cannot be modified

**Comment by AymanLyesri** [comment]
ScreenShots please, the more th better.

**Comment by AymanLyesri** [comment]
to screenshot : `CTRL + SHIFT + s`

**Comment by Blade-Dagger** [comment]
I know but it's not working ._.,  can i take a picture with mi celphone?

**Comment by AymanLyesri** [comment]
Sure

**Comment by Blade-Dagger** [comment]
![IMG_20241018_083637](https://github.com/user-attachments/assets/649f80e5-a765-4550-a015-0ce65c10ad9a)

**Comment by Blade-Dagger** [comment]
That's not me it's a friend XD

**Comment by Blade-Dagger** [comment]
And when i put the thing of the screenshot said doesn't exist the directory

**Comment by AymanLyesri** [comment]
run 
```
rm -rf $HOME/.config/ags/assets/waifu
rm -rf $HOME/.config/ags/assets/settings/settings.json
```
and do `SUPER + b` to restart the bar



> to screenshot : `CTRL + SHIFT + s`

its `SUPER + sHIFT + s`, sorry haha

**Comment by AymanLyesri** [comment]
No worries dude, am here to help, btw this gonna be fixed in the next update
If u got any suggestions or issues let me know
