### ISSUE TITLE
Blocky workspace button

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#46]
4'th workspace button haven't been rounded after closing all apps in the 3 workspace
![image](https://github.com/user-attachments/assets/102dbfcb-3e56-4f49-a163-051b940b9539)

**Comment by AymanLyesri** [comment]
Please specify the exact steps to reproduce this behavior, cause it works for me without issues

**Comment by michaelnotjackson** [comment]
Hmmm. It is this way from the start of os

**Comment by AymanLyesri** [comment]
I found out its also bugged for me in some cases, gonna be fixed in the next update
