### ISSUE TITLE
No cursor theme

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#47]
Although many apps support server-side cursors (e.g. Qt, Chromium, Electron, Hypr Ecosystem) some apps still don’t (e.g. GTK). Therefore they tend to fallback to XCursor. [As said on hyprland wiki](https://wiki.hyprland.org/Hypr-Ecosystem/hyprcursor/#important-notes) for all apps to use cursor theme of your choice you need to specify XCURSOR_THEME and XCURSOR_SIZE environment variables

**Comment by AymanLyesri** [comment]
Done and done, now using the [phinger-cursors](https://github.com/phisch/phinger-cursors) for everything
Also made cursor change theme based on current system theme
Will be pushed in the next update
![image](https://github.com/user-attachments/assets/5c52104a-74a4-4569-a7d7-f06b0f7499fe)
![image](https://github.com/user-attachments/assets/1c55b71b-7122-4d88-a2a5-7b20ee3f3d9d)
