### ISSUE TITLE
Bar after logout

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#49]
Bar behaves as if there are no apps open at current workspace after logout
![image](https://github.com/user-attachments/assets/ed5237af-c28b-48fb-a353-93afde89721a)

**Comment by AymanLyesri** [comment]
This is an issue with hyprland API in ags itself it doesn't output if the workspace is empty or not at boot-up, but after u switch workspaces it refreshes and start working normally
