### ISSUE TITLE
proj size is tooo large 

### ISSUE THREAD

**Issue by hieu-buuuk** [AymanLyesri/hyprland-conf#5]
Dude, your repository is too large, just only put needed config script inside instead of everything :_)

**Comment by AymanLyesri** [comment]
The repo is large mainly because of the wallpapers, which i think are essential.
If your main is goal is only to get the scripts, u can copy them directly instead of cloning the whole config.
Maybe in the future i could add a compression mechanism if GitHub doesn't do that already.

**Comment by AymanLyesri** [comment]
I never knew the commit history would take this much space until now
The repository has been cleaned up and reduced from 2Gb to 90mb
Sorry for the late fix

**Comment by hieu-buuuk** [comment]
Nice try :)
