### ISSUE TITLE
Battery Not Working

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#51]
Battery icon is still missing and there is no font installed by default to display unicode characters that you use for battery label
![image](https://github.com/user-attachments/assets/82e80a6b-7995-4ce5-8013-d4c32f8f017a)
Here is new ags log:
[ags.log](https://github.com/user-attachments/files/17437469/ags.log)

**Comment by AymanLyesri** [comment]
You need to make sure `ttf-jetbrains-mono-nerd` is installed for the icons to show properly.
I have no idea why the battery widget is not working on ur laptop, i made sure it works without errors in mine.
And the errors in ur log don't say much about whats happening, so i cant pinpoint the exact issue.

**Comment by michaelnotjackson** [comment]
Fixed after installing upower package
