### ISSUE TITLE
Add transparency toggle

### ISSUE THREAD

**Issue by HinaHyugaHime** [AymanLyesri/hyprland-conf#56]
add color themes other than light/dark and add a blur/unblur option
for example:
dark theme with pink
light theme with pink
dark theme with orange(or red)
light theme the same, and lastly purple of both

**Comment by HinaHyugaHime** [comment]
for example:
```/* Custom theme. Pink pastel light theme */
a.user-owner,
a.user-admin {
  background: linear-gradient(to right, orange , yellow, green, cyan, blue, violet);
  background-clip: text;
  color: transparent;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

:root {
  --body-font: cursive;
}

html {
  --pink-0: #fff0f6;
  --pink-1: #ffdeeb;
  --pink-2: #fcc2d7;
  --pink-3: #faa2c1;
  --pink-4: #f783ac;
  --pink-5: #f06595;
  --pink-6: #e64980;
  --pink-7: #d6336c;
  --pink-8: #c2255c;
  --pink-9: #a61e4d;
}

html, body[data-current-user-theme="light"] {
  --body-background-color: var(--pink-0);
  --text-color: var(--pink-9);

  --inverse-text-color: var(--pink-0);
  --muted-text-color: var(--pink-7);
  --header-color: var(--text-color);

  --link-color: var(--red-6);
  --link-hover-color: var(--red-4);

  --default-border-color: var(--pink-1);

  --error-background-color: var(--red-1);
  --success-background-color: var(--green-1);
  --target-background: var(--yellow-0);

  --subnav-menu-background-color: var(--pink-1);
  --responsive-menu-background-color: var(--pink-1);

  --form-input-text-color: var(--text-color);
  --form-input-background: var(--body-background-color);
  --form-input-border-color: var(--pink-2);
  --form-input-placeholder-text-color: var(--pink-4);
  --form-input-validation-error-border-color: var(--red-4);
  --form-input-validation-error-text-color: var(--red-5);

  --form-button-text-color: var(--text-color);
  --form-button-disabled-text-color: var(--pink-5);
  --form-button-background: var(--pink-1);
  --form-button-border-color: var(--pink-2);
  --form-button-hover-background: var(--pink-0);
  --form-button-hover-box-shadow-color: var(--pink-5);
  --form-button-active-background: var(--pink-2);

  --button-primary-text-color: var(--white);
  --button-primary-background-color: var(--link-color);
  --button-primary-hover-background-color: var(--link-hover-color);
  --button-primary-disabled-color: var(--pink-5);
  --button-outline-primary-color: var(--link-color);

  --quick-search-form-background: var(--body-background-color);

  --user-upgrade-basic-background-color: var(--blue-0);
  --user-upgrade-gold-background-color: var(--yellow-1);
  --user-upgrade-platinum-background-color: var(--blue-1);

  --table-header-border-color: var(--pink-6);
  --table-row-border-color: var(--pink-2);
  --table-row-hover-background: var(--purple-1);
  --table-even-row-background: var(--pink-1);

  --preview-pending-color: var(--blue-5);
  --preview-flagged-color: var(--red-5);
  --preview-deleted-color: var(--grey-9);
  --preview-has-children-color: var(--green-3);
  --preview-has-parent-color: var(--yellow-3);
  --preview-selected-color: rgba(0, 0, 0, 0.15);

  --preview-icon-color: var(--inverse-text-color);
  --preview-icon-background: rgba(0, 0, 0, 0.7);

  --media-asset-placeholder-background-color: var(--pink-1);

  --modqueue-tag-warning-color: var(--red-1);

  --file-upload-component-background-color: var(--body-background-color);
  --uploads-dropzone-background: var(--pink-1);
  --uploads-dropzone-progress-bar-foreground-color: var(--link-color);
  --uploads-dropzone-progress-bar-background-color: var(--link-hover-color);

  --forum-vote-up-color: var(--green-5);
  --forum-vote-meh-color: var(--orange-3);
  --forum-vote-down-color: var(--red-5);

  --forum-topic-status-new-color: var(--red-5);
  --forum-topic-status-pending-color: var(--blue-5);
  --forum-topic-status-approved-color: var(--green-5);
  --forum-topic-status-rejected-color: var(--red-5);

  --moderation-report-text-color: var(--red-5);
  --moderation-report-background-color: var(--red-1);

  --comment-sticky-background-color: var(--blue-0);

  --post-tooltip-background-color: var(--body-background-color);
  --post-tooltip-border-color: var(--pink-2);
  --post-tooltip-header-background-color: var(--pink-0);
  --post-tooltip-info-color: var(--muted-text-color);

  --post-tooltip-scrollbar-background: var(--pink-4);
  --post-tooltip-scrollbar-thumb-color: var(--pink-5);
  --post-tooltip-scrollbar-track-background: var(--pink-1);

  --user-tooltip-positive-feedback-color: var(--orange-3);
  --user-tooltip-negative-feedback-color: var(--red-5);

  --autocomplete-selected-background-color: var(--purple-1);
  --autocomplete-border-color: var(--pink-2);
  --autocomplete-tag-autocorrect-underline: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAYAAAC09K7GAAAAHElEQVQYV2NkQAL/GRj+M4IJBgY4zQhSABMEsQHMOAgCT5YN9gAAAABJRU5ErkJggg==);

  --diff-list-added-color: var(--green-5);
  --diff-list-removed-color: var(--red-5);
  --diff-list-obsolete-added-color: var(--green-7);
  --diff-list-obsolete-removed-color: var(--red-7);

  --wiki-page-versions-diff-del-background: var(--red-2);
  --wiki-page-versions-diff-ins-background: var(--green-2);

  --post-notice-border-color: var(--grey-2);
  --post-parent-notice-background: var(--green-0);
  --post-child-notice-background: var(--yellow-0);
  --post-pending-notice-background: var(--blue-1);
  --post-banned-notice-background: var(--red-1);
  --post-deleted-notice-background: var(--red-1);
  --post-resized-notice-background: var(--magenta-1);
  --post-search-notice-background: var(--pink-1);

  --post-artist-commentary-container-background: var(--pink-0);
  --post-artist-commentary-container-border-color: var(--pink-1);

  --post-upvote-color: var(--link-color);
  --post-downvote-color: var(--red-5);

  --note-body-background: #FFE;
  --note-body-text-color: var(--black);
  --note-body-border-color: var(--black);
  --note-box-border-color: var(--black);
  --note-box-shadow: 0 0 0 1px white;

  --unsaved-note-box-border-color: var(--red-4);
  --movable-note-box-border-color: var(--blue-5);
  --note-preview-border-color: var(--red-4);
  --note-preview-background: var(--note-body-background);
  --note-highlight-color: var(--blue-5);
  --note-tn-color: var(--muted-text-color);

  --series-pool-color: var(--copyright-tag-color);
  --series-pool-hover-color: var(--copyright-tag-hover-color);

  --collection-pool-color: var(--general-tag-color);
  --collection-pool-hover-color: var(--general-tag-hover-color);

  --fetch-source-data-border-color: var(--pink-2);

  --post-mode-menu-active-post-outline-color: var(--purple-2);
  --post-mode-menu-translation-background: var(--purple-2);

  --tag-count-color: var(--muted-text-color);
  --low-post-count-color: var(--red-5);

  --remove-favorite-button: var(--red-4);

  --ugoira-seek-slider-background: var(--purple-0);
  --ugoira-seek-slider-progressbar-background: var(--white);

  --keyboard-shortcut-color: var(--inverse-text-color);
  --keyboard-shortcut-background-color: var(--pink-6);

  --login-link-color: var(--red-5);
  --footer-border-color: var(--pink-1);
  --divider-border-color: var(--pink-2);

  --jquery-ui-widget-content-background: var(--body-background-color);
  --jquery-ui-widget-content-text-color: var(--text-color);

  --notice-error-background: var(--red-1);
  --notice-error-border-color: var(--red-2);
  --notice-info-background: var(--yellow-0);
  --notice-info-border-color: var(--yellow-1);

  --dtext-blockquote-border-color: var(--purple-4);
  --dtext-code-background: var(--purple-1);
  --dtext-expand-border: 1px solid var(--purple-3);
  --dtext-spoiler-background-color: var(--text-color);
  --dtext-spoiler-hover-color: var(--inverse-text-color);

  --wiki-page-other-name-background-color: var(--purple-1);

  --paginator-arrow-background-color: var(--inverse-text-color);
  --paginator-arrow-color: var(--link-color);

  --artist-tag-color: var(--purple-6);
  --artist-tag-hover-color: var(--purple-5);
  --copyright-tag-color: var(--azure-6);
  --copyright-tag-hover-color: var(--azure-5);
  --character-tag-color: var(--green-6);
  --character-tag-hover-color: var(--green-5);
  --general-tag-color: var(--link-color);
  --general-tag-hover-color: var(--link-hover-color);
  --meta-tag-color: var(--orange-6);
  --meta-tag-hover-color: var(--orange-5);

  /*--user-admin-color: var(--red-5);*/
  --user-moderator-color: var(--character-tag-color);
  --user-builder-color: var(--copyright-tag-color);
  --user-platinum-color: var(--grey-7);
  --user-gold-color: DarkGoldenrod;
  --user-member-color: var(--general-tag-color);
  --user-restricted-color: var(--pink-7);
  --user-banned-color: Chocolate;

  --user-verified-email-color: var(--green-4);
  --user-unverified-email-color: var(--yellow-2);
  
  /* #TODO */
  --news-updates-background: var(--grey-0);
  --news-updates-border-color: var(--grey-1);

  --related-tags-container-background: var(--grey-0);
  --selected-related-tag-background-color: var(--link-color);
  --selected-related-tag-color: var(--inverse-text-color);

  --inactive-artist-url-color: var(--red-6);
  --inactive-artist-url-hover-color: var(--red-5);
  --banned-artist-label-color: var(--red-5);
  --deleted-artist-label-color: var(--grey-6);
}

div#c-posts .fav-buttons button.ui-button {
  padding: .5em;
  border-radius: 100%;
}

header#top #app-name-header {
  color: var(--red-5);
}```
this is a theme for danbooru.donmai.us if you have a account you can login and change the css to this then get a idea of what I mean by pink

**Comment by HinaHyugaHime** [comment]
also add ability to select region to screenshot

**Comment by MacaylaMarvelous81** [comment]
Meta + Shift + Z takes a screenshot with a region. It requires `slurp` for the region selection.

**Comment by AymanLyesri** [comment]
The colors are already dynamic based on the current wallpaper so u could theoretically have infinite themes, the light/dark are just variations of the current colors to make them either lighter or darker
- so if u don't like the colors, change the wallpaper of the current workspace


> add a blur/unblur option

Ok, will be added in the next update
should the opacity remain the same (transparent), or should it be non transparent if there is no blur

**Comment by HinaHyugaHime** [comment]
> The colors are already dynamic based on the current wallpaper so u could theoretically have infinite themes, the light/dark are just variations of the current colors to make them either lighter or darker
> 
> * so if u don't like the colors, change the wallpaper of the current workspace
> 
> > add a blur/unblur option
> 
> Ok, will be added in the next update should the opacity remain the same (transparent), or should it be non transparent if there is no blur

Non transparent, also when I change wallpapers is no difference in colors unless I am missing something?

**Comment by AymanLyesri** [comment]
> also when I change wallpapers is no difference in colors unless I am missing something?

The terminal, ags widgets (bar, right panel, app launcher and wallpaper switcher) should change colors based on the current wallpaper
Its using pywal as the backend, make sure its installed and working

**Comment by HinaHyugaHime** [comment]
Even if I change said wallpaper in files?

**Comment by HinaHyugaHime** [comment]
> Even if I change said wallpaper in files?

And does install.sh install all that?

**Comment by HinaHyugaHime** [comment]
how do I add/remove wallpapers?

**Comment by HinaHyugaHime** [comment]
![image](https://github.com/user-attachments/assets/5a03966d-d24f-4c78-a7e4-0547134f96a5)
would like this as wallpaper

**Comment by HinaHyugaHime** [comment]
go with cyberpunk theme ui

**Comment by HinaHyugaHime** [comment]
or this 
![image](https://github.com/user-attachments/assets/cc7432ca-88c1-41a3-8bfc-f2dd54b82f7f)

**Comment by MacaylaMarvelous81** [comment]
Add them in .config/wallpapers/normal

**Comment by HinaHyugaHime** [comment]
> Add them in .config/wallpapers/normal

Will it auto color them or?

**Comment by HinaHyugaHime** [comment]
> Add them in .config/wallpapers/normal

I messed up the rice replacing the file

**Comment by HinaHyugaHime** [comment]
oh, cant replace, and gotta reboot after add

**Comment by HinaHyugaHime** [comment]
how do I remove the auto startup of spotify and the browser thing

**Comment by AymanLyesri** [comment]
add any wallpaper u like in $HOME/.config/wallpapers/normal
restart ags `SUPER + b`
restart hyprpaper using the refresh button
![image](https://github.com/user-attachments/assets/b62406ef-cd3c-47df-b0c2-ff341c7f41d8)
choose ur new wallpaper in wallpaper switcher

**Comment by AymanLyesri** [comment]
btw i added a transparency slider to be adjusted in real time, gonna be pushed in the next update

**Comment by MacaylaMarvelous81** [comment]
> how do I remove the auto startup of spotify and the browser thing

See .config/hypr/configs/exec.conf

**Comment by AymanLyesri** [comment]
> ![image](https://private-user-images.githubusercontent.com/102651522/378201724-5a03966d-d24f-4c78-a7e4-0547134f96a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDY5NjMsIm5iZiI6MTcyOTQ0NjY2MywicGF0aCI6Ii8xMDI2NTE1MjIvMzc4MjAxNzI0LTVhMDM5NjZkLWQyNGYtNGM3OC1hN2U0LTA1NDcxMzRmOTZhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxNzUxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzgwYzdiN2Q0MTE3ZWI5OThlZWU4ZGE5ZTYxNDg0NjA4OTExMzkxMmRlODI1NjY4NzE0MzBlNzY5MTdmNzI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f44dwCvgPafpCpcDOFVhcUBi95D8higaBW-JISIqnwM) would like this as wallpaper

where did u get this wallpaper from, for research purposes

**Comment by AymanLyesri** [comment]
> add any wallpaper u like in $HOME/.config/wallpapers/custom

update before doing so

**Comment by HinaHyugaHime** [comment]
Wheres the transparency slider

**Comment by HinaHyugaHime** [comment]
> > ![image](https://private-user-images.githubusercontent.com/102651522/378201724-5a03966d-d24f-4c78-a7e4-0547134f96a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDY5NjMsIm5iZiI6MTcyOTQ0NjY2MywicGF0aCI6Ii8xMDI2NTE1MjIvMzc4MjAxNzI0LTVhMDM5NjZkLWQyNGYtNGM3OC1hN2U0LTA1NDcxMzRmOTZhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxNzUxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzgwYzdiN2Q0MTE3ZWI5OThlZWU4ZGE5ZTYxNDg0NjA4OTExMzkxMmRlODI1NjY4NzE0MzBlNzY5MTdmNzI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f44dwCvgPafpCpcDOFVhcUBi95D8higaBW-JISIqnwM) would like this as wallpaper
> 
> where did u get this wallpaper from, for research purposes

https://wall.alphacoders.com/big.php?i=1377793

**Comment by HinaHyugaHime** [comment]
> btw i added a transparency slider that can be adjusted in real time, gonna be pushed in the next update

found it, but it only affects the notif bar

**Comment by HinaHyugaHime** [comment]
> > > btw i added a transparency slider that can be adjusted in real time, gonna be pushed in the next update
> > 
> > 
> > found it, but it only affects the notif bar
> 
> it should affect all of ags
> 
> maybe restart `SUPER + b`

It doesn't affect the windows I have open like chrome or discord

**Comment by AymanLyesri** [comment]
Am working on a global settings widget, gonna take a while before its ready,
Its gonna contain Hyprland options including transparency

**Comment by HinaHyugaHime** [comment]
where does it pull the wallpapers I put in from now? should really remove redundant folders, like the one thats called "fuckyou" thats some python thing I guess? weird name, then it has rules subfolder

**Comment by HinaHyugaHime** [comment]
> where does it pull the wallpapers I put in from now? should really remove redundant folders, like the one thats called "fuckyou" thats some python thing I guess? weird name, then it has rules subfolder

apparently that folder was removed I guess? I removed everything and reinstalled and its no longer there

**Comment by MacaylaMarvelous81** [comment]
You likely mistook it with [thefuck](https://github.com/nvbn/thefuck), a command line application. It’s in the pkglist.

I recommend checking configuration files before using them yourself so you can familiarize yourself with how to customize it and if it can be trusted (config files could automatically execute malicious scripts).

**Comment by HinaHyugaHime** [comment]
> You likely mistook it with [thefuck](https://github.com/nvbn/thefuck), a command line application. It’s in the pkglist.
> 
> I recommend checking configuration files before using them yourself so you can familiarize yourself with how to customize it and if it can be trusted (config files could automatically execute malicious scripts).

Does any of this rice have stuff to execute malicious scripts in it?

**Comment by AymanLyesri** [comment]
> where does it pull the wallpapers I put in from now? should really remove redundant folders, like the one thats called "fuckyou" thats some python thing I guess? weird name, then it has rules subfolder

I dont think there is a folder called "fuckyou" in the repo

**Comment by HinaHyugaHime** [comment]
> > where does it pull the wallpapers I put in from now? should really remove redundant folders, like the one thats called "fuckyou" thats some python thing I guess? weird name, then it has rules subfolder
> 
> I dont think there is a folder called "fuckyou" in the repo

It was some app installed with install.sh
