### ISSUE TITLE
Remove redundant and the default from reapplying everytime running update, add blur toggle

### ISSUE THREAD

**Issue by HinaHyugaHime** [AymanLyesri/hyprland-conf#61]
remove redundant folders and files from the .config and the repo to prevent confusion, and add ability to not replace the background selects every time update is ran

**Comment by HinaHyugaHime** [comment]
second thing would like to add is the ability to decline your PNGs in $HOME/.config/wallpapers/default and be able to use custom only make it a question if want to add /default or something

**Comment by HinaHyugaHime** [comment]
lastly remove the blur in this
![image](https://github.com/user-attachments/assets/c29a4dfb-30b3-47f0-8ee3-d5a6b97deec4)
as well as add colors to dolphin and other GTK themed appliactions based on theme

**Comment by HinaHyugaHime** [comment]
oh forgot one thing, SDDM theme maybe? optional but be nice

**Comment by HinaHyugaHime** [comment]
oh, and am I tripping or is there no logout screen or user center for changing profile picture installed by default?

**Comment by AymanLyesri** [comment]
> remove redundant folders and files from the .config and the repo to prevent confusion, 

Specify these "redundant" folders and files

> and add ability to not replace the background selects every time update is ran

Already Implemented Just read the README, all custom wallpapers should be added in the custom directory so it wouldn't be deleted after updating

**Comment by AymanLyesri** [comment]
> second thing would like to add is the ability to decline your PNGs in $HOME/.config/wallpapers/default and be able to use custom only make it a question if want to add /default or something

made it a toggle + UI changes 

![image](https://github.com/user-attachments/assets/25d29436-0e4b-46d7-907f-18b6715cbe4b)
![image](https://github.com/user-attachments/assets/c38115f1-633e-4349-98f7-dea1d3ddd3f8)

**Comment by AymanLyesri** [comment]
> lastly remove the blur in this

done, i made the blur a toggle in settings

> as well as add colors to dolphin and other GTK themed appliactions based on theme

this will take some time to get done, the tricky part is automating the changes for each user without them touching the configuration

**Note: if u have multiple issues, open each one separately, so thing would be organized for future users**

**u need to OPEN a new issue for**
- gtk themes
- sddm theme

**Comment by AymanLyesri** [comment]
> Redundant files meaning old folders that arent used upon updating cause changed

any file/folder that is removed from the repo will also be removed from the config upon updating
