### ISSUE TITLE
Gtk themes

### ISSUE THREAD

**Issue by HinaHyugaHime** [AymanLyesri/hyprland-conf#63]
Add GTK themes for thunar and such

**Comment by AymanLyesri** [comment]
Its possible but will need further configuration from each user, I'll try and find a way to automate it

**Comment by HinaHyugaHime** [comment]
> Its possible but will need further configuration from each user, I'll try and find a way to automate it

running update gives error 
```resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing sdbus-cpp (2.0.0-1) breaks dependency 'libsdbus-c++.so=1-64' required by xdg-desktop-portal-hyprland
 -> error installing repo packages```

**Comment by HinaHyugaHime** [comment]
> > Its possible but will need further configuration from each user, I'll try and find a way to automate it
> 
> running update gives error
> 
> ```
> looking for conflicting packages...
> error: failed to prepare transaction (could not satisfy dependencies)
> :: installing sdbus-cpp (2.0.0-1) breaks dependency 'libsdbus-c++.so=1-64' required by xdg-desktop-portal-hyprland
>  -> error installing repo packages```
> ```

running yay -Syyu then update after fixed it

**Comment by AymanLyesri** [comment]
> > > Its possible but will need further configuration from each user, I'll try and find a way to automate it
> > 
> > 
> > running update gives error
> > ```
> > looking for conflicting packages...
> > error: failed to prepare transaction (could not satisfy dependencies)
> > :: installing sdbus-cpp (2.0.0-1) breaks dependency 'libsdbus-c++.so=1-64' required by xdg-desktop-portal-hyprland
> >  -> error installing repo packages```
> > ```
> 
> running yay -Syyu then update after fixed it

How is this related to the issue + just running yay -Syu fixes it

**Comment by HinaHyugaHime** [comment]
> > > > Its possible but will need further configuration from each user, I'll try and find a way to automate it
> > > 
> > > 
> > > running update gives error
> > > ```
> > > looking for conflicting packages...
> > > error: failed to prepare transaction (could not satisfy dependencies)
> > > :: installing sdbus-cpp (2.0.0-1) breaks dependency 'libsdbus-c++.so=1-64' required by xdg-desktop-portal-hyprland
> > >  -> error installing repo packages```
> > > ```
> > 
> > 
> > running yay -Syyu then update after fixed it
> 
> How is this related to the issue + just running yay -Syu fixes it

Didnt know where else to tell you it

**Comment by AymanLyesri** [comment]
I've change the current theme, now using [WhiteSur](https://github.com/vinceliuice/WhiteSur-gtk-theme)

**Comment by HinaHyugaHime** [comment]
> I've change the current theme, now using [WhiteSur](https://github.com/vinceliuice/WhiteSur-gtk-theme)

Didnt change my dolphin theme for some reason

**Comment by AymanLyesri** [comment]
Dolphin is built on Qt not Gtk, i recommend u use ranger, its terminal based so the colors will be dynamic based on the wallpaper + (light/dark)

**Comment by HinaHyugaHime** [comment]
Does it have the same right click options?

**Comment by AymanLyesri** [comment]
no, its terminal based, all options are through keyboard shortcuts

**Comment by HinaHyugaHime** [comment]
Rather have a gtk file manager

**Comment by AymanLyesri** [comment]
try thunar, its pretty good and based on gtk, maybe i'll even make it the default file manager for this config

**Comment by AymanLyesri** [comment]
if there are better themes let me know, otherwise am closing this issue as solved
