### ISSUE TITLE
SDDM themes

### ISSUE THREAD

**Issue by HinaHyugaHime** [AymanLyesri/hyprland-conf#64]
Add SDDM themes perhaps something simple such as transparent/slightly blurred login with background

**Comment by AymanLyesri** [comment]
I've replaced sddm altogether with LightDM, its fast and customizable, also added this [theme](https://litarvan.github.io/lightdm-webkit-theme-litarvan/#/base/splash) to it

**Comment by HinaHyugaHime** [comment]
> I've replaced sddm altogether with LightDM, its fast and customizable, also added this [theme](https://litarvan.github.io/lightdm-webkit-theme-litarvan/#/base/splash) to it
> 
> EDIT: the LightDM setup is through the install script not update

was gonna say that it didn't work through update
