### ISSUE TITLE
Logout screen and user center App

### ISSUE THREAD

**Issue by HinaHyugaHime** [AymanLyesri/hyprland-conf#65]
Add logout/shutdown screen and add a app for user center to change profile picture assuming we only install the rice

**Comment by AymanLyesri** [comment]
here it is, but still WIP, gonna add more things to it
![image](https://github.com/user-attachments/assets/38602612-b183-4416-b1c2-518ecb4a1e37)

**Comment by HinaHyugaHime** [comment]
also can you remove the auto executing zen browser and spotify? I use chrome and spotify adblock so its kind of annoying

**Comment by AymanLyesri** [comment]
> also can you remove the auto executing zen browser and spotify? I use chrome and spotify adblock so its kind of annoying

I'll make the exec file unique to the user so it wont change when updating, then u could just replace zen with chrome etc...
