### ISSUE TITLE
Keyboard Config

### ISSUE THREAD

**Issue by Blade-Dagger** [AymanLyesri/hyprland-conf#68]
This is more a question than a issue, can i change my keyboard ditribution.

**Comment by AymanLyesri** [comment]
yes, the keyboard configuration is stored here: `$HOME/.config/hypr/configs/custom/keyboard.conf`
normally it would look something like this :
```
input { 
	kb_layout=us,us 
	kb_variant=,dvorak 
}
```
see [here](https://wiki.hyprland.org/Configuring/Variables/#input) for more info
if u have any questions let me know

**Comment by AymanLyesri** [comment]
No updates, closing this issue..
