### ISSUE TITLE
hyprland doesnt start

### ISSUE THREAD

**Issue by Blade-Dagger** [AymanLyesri/hyprland-conf#69]
Hyprland does not start automatically; I have to turn on the PC and it shows Arch like when I just installed it, and I have to type 'hyprland' to start it. How can I make it start automatically?

**Comment by HinaHyugaHime** [comment]
Temp fix til he can fix this: 
Ctrl+alt+F3
Enter username then password after
`sudo systemctl disable lightdm`
If you had gdm replace sddm with gdm in this command
`sudo systemctl enable sddm`
`sudo systemctl restart display-manager`
Then login

**Comment by AymanLyesri** [comment]
U need to update through the install script this time, and say `yes` to **installing necessary packages and lightdm setup**
This is a one time thing, and then u could just run `update` for updating in the future.
![image](https://github.com/user-attachments/assets/0cfdce16-ed0e-45c1-b40c-453ab0028670)
![image](https://github.com/user-attachments/assets/924e8b26-01fb-43cf-a4fc-0665b133ffdd)

**Comment by HinaHyugaHime** [comment]
> U need to update through the install script this time, and say `yes` to **installing necessary packages and lightdm setup** This is a one time thing, and then u could just run `update` for updating in the future. ![image](https://private-user-images.githubusercontent.com/80812811/379692241-0cfdce16-ed0e-45c1-b40c-453ab0028670.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NjAzMjUsIm5iZiI6MTcyOTc2MDAyNSwicGF0aCI6Ii84MDgxMjgxMS8zNzk2OTIyNDEtMGNmZGNlMTYtZWQwZS00NWMxLWI0MGMtNDUzYWIwMDI4NjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA4NTM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0M2JiYzk4YzFlMzUzYTRjZTRkOGMyNGMzNWNhMjdjYTUxYzRhMGI0ZDRmYWU2MWZiMTQ3ZTAyZTg2MmFiNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XShdgMdiNLZ5cAZeIEfmi2d4zUrWu_rYvICwB4Yi9vA) ![image](https://private-user-images.githubusercontent.com/80812811/379692301-924e8b26-01fb-43cf-a4fc-0665b133ffdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NjAzMjUsIm5iZiI6MTcyOTc2MDAyNSwicGF0aCI6Ii84MDgxMjgxMS8zNzk2OTIzMDEtOTI0ZThiMjYtMDFmYi00M2NmLWE0ZmMtMDY2NWIxMzNmZmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA4NTM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYThkYjlmZDg1NzhiMTA1ZjBlZmYxYzc2MTVkMzA5ODZhM2U1ZTNiOGEyMmI0YTlkNmFiNDRhZDE2OGRjM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m3o55J6NLOGvlchRj91ivZf5uzJCBk7Gp81_pBuxFEw)

We did that but after entering password it just restarts LightDM, not login

**Comment by AymanLyesri** [comment]
So lightdm works, but it dosent log the user into hyprland
![image](https://github.com/user-attachments/assets/c10a41f1-7427-490c-b5d3-38b2d2ab8c3f)
do u have an option for `Hyprland` in the login menu, if so select it and then log in

**Comment by HinaHyugaHime** [comment]
> So lightdm works, but it dosent log the user into hyprland ![image](https://private-user-images.githubusercontent.com/80812811/379731269-c10a41f1-7427-490c-b5d3-38b2d2ab8c3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODA5MDgsIm5iZiI6MTcyOTc4MDYwOCwicGF0aCI6Ii84MDgxMjgxMS8zNzk3MzEyNjktYzEwYTQxZjEtNzQyNy00OTBjLWI1ZDMtMzhiMmQyYWI4YzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDE0MzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2N2ViNjc5NzRjNmJjNmY0OGEyNjExYmQxNjYyNDAzZmFkNGVhYjE3OWZiNDViNzQ1YjY2NjEzZDczMzY2ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TnHaBXvJkeHPfwPNtMK31fPz6fOepE4x8hFK4djXI6E) do u have an option for `Hyprland` in the login menu, if so select it and then log in

I select hyprland its the only WM I have, it just refreshes LightDM

**Comment by Blade-Dagger** [comment]
It happened to me too.

**Comment by AymanLyesri** [comment]
I found that lightdm might have some issues with wayland distros (hyprland)
Am reverting back to sddm using this [theme](https://github.com/stepanzubkov/where-is-my-sddm-theme)

**Comment by AymanLyesri** [comment]
Hotfix is pushed, run the install and let me know

**Comment by Blade-Dagger** [comment]
it works, thanks man you are the best

**Comment by AymanLyesri** [comment]
No problem am here to fix things :)
if u have any suggestions let me know
