### ISSUE TITLE
Hyprland bool vars

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#70]
https://github.com/AymanLyesri/hyprland-conf/blob/6df4082f1f26936a665a0046591ac345bc71da1d/.config/hypr/configs/general.conf#L9
Hyprlands general:resize_on_border variable isn't recognized as set to true, as it is. It works when it is set to true instead of 1. I suppose it is the same for all bool variables

**Comment by AymanLyesri** [comment]
It works either way, still, better to set it as a boolean
will be fixed in the next update

**Comment by michaelnotjackson** [comment]
> It works either way, still, better to set it as a boolean will be fixed in the next update

Hmmm. I definitely can't resize windows, when it is set to when yet I can when it is set to true

**Comment by AymanLyesri** [comment]
It definitely should work:
![image](https://github.com/user-attachments/assets/d2f81d5c-bcbd-4f1b-b7bb-9650fd2e80f6)
