### ISSUE TITLE
SDDM themes

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#71]
SDDM theme was not set after installation.
Rerunning SDDM.sh results in the `chmod: cannot access '/usr/share/backgrounds': No such file or directory` yet theme is being set to black background and user input in the middle of the screen as asterisks

**Comment by AymanLyesri** [comment]
this is the intended behavior for now, I'll make tweaks to the background and the input,
do u have a suggestion for the background

**Comment by michaelnotjackson** [comment]
> this is the intended behavior for now, I'll make tweaks to the background and the input, do u have a suggestion for the background

I think that some image will do well, but maybe you should add an ability to switch DEs

**Comment by HinaHyugaHime** [comment]
I'm running sober version of this https://github.com/Rokin05/sddm-themes

**Comment by HinaHyugaHime** [comment]
https://github.com/3ximus/aerial-sddm-theme theres also something like this or this
https://github.com/MarianArlt/sddm-sugar-dark

**Comment by HinaHyugaHime** [comment]
overall can search themes using https://github.com/search?q=sddm&type=repositories

**Comment by HinaHyugaHime** [comment]
if you want something anime themed there is stuff like this https://github.com/aczw/sddm-theme-corners

**Comment by HinaHyugaHime** [comment]
@AymanLyesri can probably make something good using this one tbh

> if you want something anime themed there is stuff like this https://github.com/aczw/sddm-theme-corners

**Comment by HinaHyugaHime** [comment]
would be nice if you could make it like this one but it looks like the guy who made it is inactive https://github.com/aczw/sddm-theme-corners/blob/main/docs/sky.png

**Comment by AymanLyesri** [comment]
Thanks for the suggestions! I'm aiming for something lightweight and performant. Since we won’t be spending much time on the login screen, I’d prefer to keep it snappy rather than adding more animations.

This is the current [theme](https://github.com/stepanzubkov/where-is-my-sddm-theme)

> but maybe you should add an ability to switch DEs

its already supported, I just need to toggle it

**And for the wallpapers**
I'll add an toggle to set the sddm wallpaper from the wallpaper switcher
