### ISSUE TITLE
Cursor theme

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#74]
1) Cursor theme for GTK apps is not being set upon system boot
2) Not all apps that can't use hyprcursor can use gtk's cursor system. To make it work for all apps you also need to set XCURSOR_THEME and XCURSOR_SIZE env variable to a valid xcursor theme (in our case it would be phinger-cursors-dark or phinger-cursors-light)
P.S. Can't provide screenshots, because hyprshot hides cursor upon taking a screenshot

**Comment by AymanLyesri** [comment]
Yeah, it also happens to me sometimes, not sure what is the issue.
I'll see what i can do.
