### ISSUE TITLE
Everything sometimes stops working

### ISSUE THREAD

**Issue by Blade-Dagger** [AymanLyesri/hyprland-conf#77]
I have no idea why it happens. It's something random sometimes it happens, sometimes it doesn’t. Basically, the top bar and the sidebar stop functioning, and nothing happens when I hover over them or click. After a while, they start working again.

**Comment by AymanLyesri** [comment]
I also encountered this problem, I've pushed an update, test it and let me know

**Comment by Blade-Dagger** [comment]
Okay, I'll try it and let you know what happens.

**Comment by HinaHyugaHime** [comment]
I updated and am now facing the same issue

**Comment by AymanLyesri** [comment]
@Blade-Dagger any update?

**Comment by Blade-Dagger** [comment]
For me Is working good.

**Comment by AymanLyesri** [comment]
Good, I'll keep this issue open for one more day and then I'll close it

**Comment by HinaHyugaHime** [comment]
Im having issues after update tho..

**Comment by AymanLyesri** [comment]
What kind of issues?

**Comment by HinaHyugaHime** [comment]
Severe lagg and stuttering on ags

**Comment by AymanLyesri** [comment]
R u sure u running the latest version

**Comment by HinaHyugaHime** [comment]
Yeah, I updated it yesterday

**Comment by AymanLyesri** [comment]
No updates, closing this issue..
