### ISSUE TITLE
need it to stop forcing

### ISSUE THREAD

**Issue by HinaHyugaHime** [AymanLyesri/hyprland-conf#79]
It keeps force opening spotify, and so on whenever I swap to it's specified tab and when I try to save images for example in regular discord it tries to launch armcord but I don't want to use armcord.

**Comment by HinaHyugaHime** [comment]
this is a long standing issue btw just getting annoyed by it, whenever I swap to zen's dedicated tab it starts up it, or spotify it starts up spotify after

**Comment by michaelnotjackson** [comment]
> this is a long standing issue btw just getting annoyed by it, whenever I swap to zen's dedicated tab it starts up it, or spotify it starts up spotify after

You can change this behavior in ~/.config/hypr/configs/window_rules.conf

**Comment by AymanLyesri** [comment]
I'll make it unique to each user so it wont get overwritten after updating
