### ISSUE TITLE
Cursor theme

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#81]
GTK cursor theme is still not being set at system startup
![image](https://github.com/user-attachments/assets/23990e3b-12f9-4461-9820-08d0f9701f6d)

**Comment by AymanLyesri** [comment]
Silly me i messed up the script path that changes the cursor theme, its fixed now, test it and let me know
```
update dev
```

**Comment by michaelnotjackson** [comment]
> Silly me i messed up the script path that changes the cursor theme, its fixed now, test it and let me know
> 
> ```
> update dev
> ```

Fixed
