### ISSUE TITLE
add bluetooth support

### ISSUE THREAD

**Issue by HinaHyugaHime** [AymanLyesri/hyprland-conf#83]
add bluetooth widget and have it install bluetooth necessities

**Comment by AymanLyesri** [comment]
the bluetooth widget is already displayed through sys-tray

**Comment by HinaHyugaHime** [comment]
I dont see it with my bluetooth enabled

**Comment by AymanLyesri** [comment]
It should look something like this
![image](https://github.com/user-attachments/assets/27ee05a8-c12d-4f28-8e9c-37a2ee0ebbf1)

when double clicked it opens the interface
![image](https://github.com/user-attachments/assets/cc905f97-aff6-4289-ab8e-0667d5133036)


check if `blueman-applet` is running

**Comment by HinaHyugaHime** [comment]
> It should look something like this ![image](https://private-user-images.githubusercontent.com/80812811/381577145-27ee05a8-c12d-4f28-8e9c-37a2ee0ebbf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTg5NTYsIm5iZiI6MTczMDI5ODY1NiwicGF0aCI6Ii84MDgxMjgxMS8zODE1NzcxNDUtMjdlZTA1YTgtYzEyZC00ZjI4LThlOWMtMzdhMmVlMGViYmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE0MzA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MzI3NDkyZTMwYzU1Nzk1MmE3YWQ4NjJhMDBmMjFlODhlMWM2ZDUxZjhkZTFiYmQyMjFkYjZmY2JjYjg0NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wLXPpX1LNR1unHYh4pGjk3JT9dk8dcEeeAwk3cX5MEU)
> 
> when double clicked it opens the interface ![image](https://private-user-images.githubusercontent.com/80812811/381579580-cc905f97-aff6-4289-ab8e-0667d5133036.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTg5NTYsIm5iZiI6MTczMDI5ODY1NiwicGF0aCI6Ii84MDgxMjgxMS8zODE1Nzk1ODAtY2M5MDVmOTctYWZmNi00Mjg5LWFiOGUtMDY2N2Q1MTMzMDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE0MzA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3M2ViYmVlOTJiYWFjZmM1OTQ5MmZhNWJiNWJlMzJkZDljNDEyMjNiOWI4OWFjZjU4NTMwYzQwYzYxYWVkNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k1SqnnmfnuBSTxKeaCZGKb4rFX97zq3UTBD01FiyR1o)
> 
> check if `blueman-applet` is running

I don't recieve that first picture bluetooth icon, have to manually type in and enable BT and it still doesnt show

**Comment by AymanLyesri** [comment]
so its a problem with `blueman-applet` itself, maybe ur machine dosent support it

**Comment by HinaHyugaHime** [comment]
I ran blueman-applet and got this ```❯ blueman-applet 
blueman-applet 10.22.57 WARNING  PluginManager:93 load_plugin: Failed to start plugin GameControllerWakelock: Only X11 platform is supported
blueman-applet 10.22.57 WARNING  PluginManager:150 __load_plugin: Not loading PPPSupport because its conflict has higher priority
blueman-applet 10.22.57 WARNING  PluginManager:150 __load_plugin: Not loading DhcpClient because its conflict has higher priority
```

**Comment by HinaHyugaHime** [comment]
not sure why but now its showing up

**Comment by HinaHyugaHime** [comment]
> so its a problem with `blueman-applet` itself, maybe ur machine dosent support it

ok, so assume I am just installing arch, what would I install to get just this rice?

**Comment by HinaHyugaHime** [comment]
can we just discuss this over discord? my @ is Hina.miku

**Comment by AymanLyesri** [comment]
> not sure why but now its showing up

good

> > so its a problem with `blueman-applet` itself, maybe ur machine dosent support it
> 
> ok, so assume I am just installing arch, what would I install to get just this rice?

> Also the pfp change doesnt change required files

i dont quite understand

> can we just discuss this over discord? my @ is Hina.miku

![image](https://github.com/user-attachments/assets/2aed9bcc-cce7-4a7d-b717-768a05d9f7b9)

here is my at @ lilayman
