### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by HinaHyugaHime** [AymanLyesri/hyprland-conf#84]
update dependencies and have it generate service files for stuff that needs it for example wireplumber and such, pipewire-session-manager is outdated and deprecated

**Comment by HinaHyugaHime** [comment]
also I have no idea why, but when I installed everything using your install it had bad packages or something cause I was unable to create the service files until reinstall

**Comment by AymanLyesri** [comment]
the pkglist dosent include wireplumber nor pipewire-session-manager, only pipewire
See [here](https://github.com/AymanLyesri/hyprland-conf/blob/master/.config/hypr/pacman/pkglist.txt) if any packages are deprecated and let me know

**Comment by HinaHyugaHime** [comment]
ahh, I mustve been confused, my bad.

**Comment by AymanLyesri** [comment]
No worries
