### ISSUE TITLE
GTK Theme

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#85]
whitesur light is not light
![image](https://github.com/user-attachments/assets/1b6c078e-d08d-4ba3-a24a-c6310f5e63b8)

**Comment by AymanLyesri** [comment]
run 
```
gsettings set org.gnome.desktop.interface gtk-theme WhiteSur-Light
```

and
```
gsettings set org.gnome.desktop.interface gtk-theme WhiteSur-Dark
```
and see if it changes, it should work
it works on both my laptop in desktop, maybe u didn't install dependencies while running `update`

**Comment by michaelnotjackson** [comment]
Light theme is not white even after reinstalling whitesur-light theme package

**Comment by AymanLyesri** [comment]
u need to install whitesur-gtk-theme from the aur it got both

**Comment by michaelnotjackson** [comment]
> u need to install whitesur-gtk-theme from the aur it got both

It is installed
![image](https://github.com/user-attachments/assets/9d1a0dcc-da06-436f-887c-98139bb7fa87)

**Comment by AymanLyesri** [comment]
![image](https://github.com/user-attachments/assets/0c57f9cb-d5a5-4d1f-bf46-bffb57d33b5f)
the themes folder should look something like this

**Comment by michaelnotjackson** [comment]
It looks almost same to me
![image](https://github.com/user-attachments/assets/c72f16a4-2727-4303-97d6-5f450ee045e9)

**Comment by AymanLyesri** [comment]
Strange, if the light theme folder exist, idk why it dosent work

**Comment by michaelnotjackson** [comment]
I found out what was happening. I had color-scheme set to prefer-dark, which turns whitesur-light into it's dark variant
