### ISSUE TITLE
Make arch install script

### ISSUE THREAD

**Issue by HinaHyugaHime** [AymanLyesri/hyprland-conf#86]
Make a arch install script to install just hyprland, and the rice set up with all required programs and apps using install.sh from repo to install OS and all required programs and such so can have this rice on first bootup no issues

**Comment by AymanLyesri** [comment]
There is already a native arch install script see [here](https://wiki.archlinux.org/title/Archinstall)

so the new user need to input only two commands: `archinstall` + the curl command i provide

**Comment by HinaHyugaHime** [comment]
> There is already a native arch install script see [here](https://wiki.archlinux.org/title/Archinstall)
> 
> so the new user need to input only two commands: `archinstall` + the curl command i provide

but what environment or whatever do I add in archinstall

**Comment by AymanLyesri** [comment]
select hyprland in profile section
