### ISSUE TITLE
Blur

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#88]
https://github.com/AymanLyesri/hyprland-conf/blob/cf43ab0c97f9f86e55e5a97b6acb3bb5ad77f991/.config/hypr/configs/general.conf#L86C3-L99C4
Move this part into custom/blur.conf

**Comment by AymanLyesri** [comment]
blur toggle is already custom through settings widget, I'll add size and passes to it
Other options are better to be left in the global config
