### ISSUE TITLE
Hello, I have encountered some problems during use.

### ISSUE THREAD

**Issue by Yakumo-Yukari** [AymanLyesri/hyprland-conf#9]
https://github.com/AymanLyesri/hyprland-conf/blob/master/.config/hypr/hyprland.conf#L7C1-L7C39

The custom file is missing in the configs directory.

The ags bar and the right panel are not displaying. I'm not sure where the problem is.

**Comment by michaelnotjackson** [comment]
Hi. I faced similar issue with ags. For me the problem was the hardcoded paths to the authors home directory in the ags config. You can try replacing them with your own.

**Comment by michaelnotjackson** [comment]
> > Hi. I faced similar issue with ags. For me the problem was the hardcoded paths to the authors home directory in the ags config. You can try replacing them with your own.
> 
> Thanks for the advice, can you tell me which files are involved?

I don't remember which files were involved, but I was able to find them by running `grep -lir "ayman"` in the `$HOME/.config` directory.

**Comment by AymanLyesri** [comment]
Hi, I've updated all the paths to use relative paths instead of hard-coded ones. Please let me know if this resolves the issue.

If you encounter any problems, feel free to reach out, and I'd be happy to assist in fixing them.

**Comment by AymanLyesri** [comment]
Can u post a screenshot of the output when running ags, cause i don't see any errors in previous picture only a CRITICAL title

**Comment by AymanLyesri** [comment]
The locale error is a gtk problem, try this fix:
In /etc/locale.gen, uncomment the locales that you are using and run **locale-gen** as root.

here is the line that i uncommented for example
![image](https://github.com/user-attachments/assets/5452b440-875f-4c50-ac85-0bd7b5cf84a1)

**Comment by AymanLyesri** [comment]
yeah maybe the problem is with ur distro, try that and let me know

**Comment by AymanLyesri** [comment]
no response, am closing the issue
