### ISSUE TITLE
AGS crash

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#91]
AGS doesn't start after pulling latest commit. Log: 
[ags.log](https://github.com/user-attachments/files/17597468/ags.log)

**Comment by AymanLyesri** [comment]
pushed a hotfix, update and let me know

**Comment by michaelnotjackson** [comment]
It launches, but backgrounds are missing
![image](https://github.com/user-attachments/assets/88df841f-aa54-495c-acdc-e3857cc558b3)

**Comment by AymanLyesri** [comment]
maybe you've set opacity to low

**Comment by michaelnotjackson** [comment]
> maybe you've set opacity to low ![image](https://private-user-images.githubusercontent.com/80812811/382242394-2e15ab6c-6a51-4af1-bd54-94afc0a8ff47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NjQ1OTgsIm5iZiI6MTczMDQ2NDI5OCwicGF0aCI6Ii84MDgxMjgxMS8zODIyNDIzOTQtMmUxNWFiNmMtNmE1MS00YWYxLWJkNTQtOTRhZmMwYThmZjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDEyMzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZTYxYjZjN2JiZWEzN2NmMDdiYjUyODkyZDgyM2YxZGQwZmM2NjYwMzQ0MDA3NjMxYWE1ZjNlMDFkMDZmMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.45TWy4oza54A0ci0So3IdkjPdcicTTJ9weyyeWgchzY)

Yeah, it was set to low. But it's kinda confusing, that low is at the top and max is at the bottom. Could you swap them?
