### ISSUE TITLE
Media keys

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#92]
Could you add binds and gui for changing volume and brightness? Maybe smth similar to [SwayOSD](https://github.com/ErikReider/SwayOSD)

**Comment by AymanLyesri** [comment]
added OSD for volume and brightness, its still WIP, let me know if anything needs to be added to it

**Comment by michaelnotjackson** [comment]
When I press volume/brightness keys nothing happens (from commit I think that it is an intended behavior for now).
And what font is needed for this symbols to be rendered correctly?
![image](https://github.com/user-attachments/assets/46d49ccd-9eac-4c45-8aa5-7454ece40ea3)

**Comment by AymanLyesri** [comment]
> When I press volume/brightness keys nothing happens

The osd only appear when changing brightness/volume value (e.g: when using slider)

> And what font is needed for this symbols to be rendered correctly?

its `ttf-jetbrains-mono-nerd`, for some reason it doesn't work on browser, never knew why

**Comment by michaelnotjackson** [comment]
> The osd only appear when changing brightness/volume value (e.g: when using slider)

I guess it would be nice to have media keys (for example XF86AudioRaiseVolume) binded to changing volume and brightness by default (m.b. through brightnessctll and wpctl)

**Comment by michaelnotjackson** [comment]
> The osd only appear when changing brightness/volume value (e.g: when using slider)

OSD doesn't appear when I'm changing brightness

**Comment by AymanLyesri** [comment]
I still need to test things related to brightness in my laptop, dont worry it will all be fixed

**Comment by AymanLyesri** [comment]
all fixed, update and let me know

**Comment by michaelnotjackson** [comment]
> all fixed, update and let me know

Yep. Works good now. Thanks!

**Comment by AymanLyesri** [comment]
Happy to help, Let me know if u got any other suggestions

**Comment by Blade-Dagger** [comment]
only the brightness control works. ._.

**Comment by michaelnotjackson** [comment]
> only the brightness control works. ._.

What do you use for audio? In the current script audio controls are relying on on wireplumber to work.

P.S. Better start a new issues. AFAIK author doesn't get notified about anything happening in closed issues
