### ISSUE TITLE
Make a new installer

### ISSUE THREAD

**Issue by HinaHyugaHime** [AymanLyesri/hyprland-conf#94]
Try making a installer like https://github.com/mylinuxforwork/dotfiles
Including SDDM  all required files for a minimal arch setup including but not limited to pipewire, bluez, the rice, (systemd ) and others

**Comment by AymanLyesri** [comment]
This installer already assume u have a base arch Linux install, it doesn't install Linux firmware / format disk / set locals.... 
It runs on already installed arch distro, it installs Hyprland and the rest of the usual configuration.
i'll add hyprland to the pkglist if thats what ur asking.

**Comment by HinaHyugaHime** [comment]
It is needing hyprland to the package list, but also making it more tidy by cleaning up certain files like removing GDM and lightdm or whatever it was, the SH's and keeping sddm and have it do the SDDM stuff, aswell as adding required packages for daily use like thunar, or other apps like that for people who want GTK based utilities

**Comment by AymanLyesri** [comment]
>  but also making it more tidy by cleaning up certain files like removing GDM and lightdm or whatever it was

pkglist only contains sddm

> aswell as adding required packages for daily use like thunar, or other apps like that for people who want GTK based utilities

Thunar is in review process (by me) so if i like it I'll add it as a dependency, do u have any other GTK utilities u want me to try/add

**Comment by HinaHyugaHime** [comment]
> > but also making it more tidy by cleaning up certain files like removing GDM and lightdm or whatever it was
> 
> pkglist only contains sddm
> 
> > aswell as adding required packages for daily use like thunar, or other apps like that for people who want GTK based utilities
> 
> Thunar is in review process (by me) so if i like it I'll add it as a dependency, do u have any other GTK utilities u want me to try/add

Yea but the files contain a gdm and lightdm SH file

**Comment by AymanLyesri** [comment]
done, i removed lightdm/gdm scripts
