### ISSUE TITLE
Add a application browser

### ISSUE THREAD

**Issue by HinaHyugaHime** [AymanLyesri/hyprland-conf#99]
Add a clickable application browser to the bar to view all apps and select what you want/need

**Comment by AymanLyesri** [comment]
already done
![image](https://github.com/user-attachments/assets/9681e64c-c330-435e-af99-851eecf45f60)

![image](https://github.com/user-attachments/assets/13c3ecb7-0c5c-45b6-9f9d-d2b78ce90214)

**Comment by HinaHyugaHime** [comment]
Nah I mean that shows All apps when open like a file explorer but apps

**Comment by AymanLyesri** [comment]
i don't think that would achieve anything new, just gonna be more bloat slowing down the system,
Generally when the user searches for an app, he already knows its name or a part of it, so no need to display all apps for just the sake of it
